### ISSUE TITLE
No response when clicking Evernote icon

### ISSUE THREAD

**Issue by TajviaWillis** [grobgl/n1-evernote#2]
Ran Nylas in Debug mode and got the following:
</blockquote>
</div>
</div></div></blockquote></div><br/></div></en-note>
Error: Client not defined(…)
TypeError: Cannot read property 'getNoteStore' of undefined
    at _EvernoteClient.makeNote (/Users/tajviawillis/.nylas/packages/n1-evernote/lib/evernote-client.coffee:48:27)
    at _EvernoteClient.makeNote (/Users/tajviawillis/.nylas/packages/n1-evernote/lib/evernote-client.coffee:1:1)
    at /Users/tajviawillis/.nylas/packages/n1-evernote/lib/ui/message-action.cjsx:36:20
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/lib/html2enml.js:130:16
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:726:13
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:52:16
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:269:32
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:44:16
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:723:17
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:167:37
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:209:22)
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/lib/html2enml.js:151:24
    at /Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/Users/tajviawillis/.nylas/packages/n1-evernote/node_modules/htmltoenml/node_modules/async/lib/async.js:262:13)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback](timers.js:533:5) Object {url: "/Users/tajviawillis/.nylas/packages/n1-evernote/lib/evernote-client.coffee", line: 48, column: 27}
Uncaught TypeError: Cannot read property 'getNoteStore' of undefined

**Comment by unleashed13** [comment]
Same here, not working. No response when clicking Evernote icon

**Comment by unleashed13** [comment]
Has this been sorted?

**Comment by j-peeters** [comment]
Same for me doesn't work.

**Comment by mrvs70** [comment]
Same here!

**Comment by grobgl** [comment]
Apologies everyone, I dropped this project for now. The main issue is that I need a reliable HTML to Evernote markup converter (find my attempt [here](https://github.com/grobgl/node-html2enml)).
